version: '3.8'

services:
  api:
    build: 
      context: ../api-server/
    volumes: 
      - ./private.key:/src/private.key
      - ./public.key:/src/public.key
      - /src/node_modules
    environment:
      NODE_ENV: production
      M_PROD: 'true'
      NEXTCLOUD_USERNAME: max
      NEXTCLOUD_PASSWORD: mustermann
      NEXTCLOUD_URL: https://cloud.example.com
    networks:
      - plaudio-network
  nginx:
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ./client:/usr/share/nginx/client
    networks:
      - plaudio-network
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  plaudio-network: